language: go
sudo: false
env:
  # Turn off go module support, as the go.sum files in go/ and go/codec/
  # need to be populated with their cyclic checksums, so CI's mod=readonly will not work.
  - GO111MODULE=off
go:
  - master
  - 1.15.x
  - 1.14.x
  - 1.13.x
  - 1.12.x
  - 1.11.x
  # go testing suite support, which we use, was introduced in go 1.7
  # testing.TB, TB.Helper() was introduced in go 1.9
  # Consequently, tests will only compile for go 1.9+
script:
  - go test -tags "alltests" -run Suite -coverprofile coverage.txt github.com/ugorji/go/codec
  - go test -tags "alltests safe" -run Suite -coverprofile coverage.safe.txt github.com/ugorji/go/codec
  - go test -tags "alltests codecgen" -run Suite -coverprofile coverage.codecgen.txt github.com/ugorji/go/codec
  # we use if block below, so that we still return with success even if skipped.
  # Previously, we used [[...]] && go test ..., which returned exit code 0 and broke the build.
  - |
    if [[ "${TRAVIS_GO_VERSION}" == "1.11.x" ]]; then
    GOARCH=386 go test -tags "alltests" -run Suite -coverprofile coverage.386.txt github.com/ugorji/go/codec
    fi
  - |
    if [[ "${TRAVIS_GO_VERSION}" == "1.12.x" ]]; then
    GOARCH=386 go test -tags "alltests safe" -run Suite -coverprofile coverage.386.safe.txt github.com/ugorji/go/codec
    fi
  - |
    if [[ "${TRAVIS_GO_VERSION}" == "1.13.x" ]]; then
    GOARCH=386 go test -tags "alltests codecgen" -run Suite -coverprofile coverage.386.codecgen.txt github.com/ugorji/go/codec
    fi
  - |
    if [[ "${TRAVIS_GO_VERSION}" == "1.14.x" ]]; then
    echo "XXXX RACE notfastpath" && go test "-race" -tags "alltests notfastpath" -run Suite -coverprofile coverage.race.txt github.com/ugorji/go/codec;
    fi
  - |
    if [[ "${TRAVIS_GO_VERSION}" == "1.15.x" ]]; then
    echo "XXXX RACE" && go test "-race" -tags "alltests" -run Suite -coverprofile coverage.race.txt github.com/ugorji/go/codec;
    fi

after_success:
  - bash <(curl -s https://codecov.io/bash)
